# Generated by Django 5.1.4 on 2024-12-07 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=50)),
                ('assembled_at', models.DateTimeField(auto_now_add=True)),
                ('avionics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_avionics', to='parts.part')),
                ('fuselage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_fuselage', to='parts.part')),
                ('tail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_tail', to='parts.part')),
                ('wing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_wing', to='parts.part')),
            ],
        ),
    ]
