# Generated by Django 5.1.4 on 2024-12-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='avionics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_avionics', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='fuselage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_fuselage', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_tail', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='wing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_wing', to='parts.part'),
        ),
    ]
