# Generated by Django 5.1.4 on 2024-12-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='responsible_part_type',
            field=models.CharField(choices=[('Wing', 'Wing'), ('Fuselage', 'Fuselage'), ('Tail', 'Tail'), ('Avionics', 'Avionics'), ('Assembly', 'Assembly')], max_length=50, unique=True),
        ),
    ]
