name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: ls
        run: |
          pwd
          ls
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./src/docker-compose.yaml"
      - name: Send request to localhost:8000
        run: |
          start_time=$(date +%s)
          while true; do
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000)
            echo "HTTP Status: $response"
            if [ "$response" -eq 200 ]; then
              echo "Received 200 status code. Proceeding with teardown."
              break
            fi
            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))
            if [ "$elapsed_time" -ge 180 ]; then
              echo "Timeout reached (3 minutes). Exiting loop."
              break
            fi
            sleep 1
          done
      - name: Tear down containers
        run: |
          docker-compose down
