name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/compose-action@v2

      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.yaml up -d --build

      - name: Run account app unit tests
        run: |
          docker-compose exec -T web python manage.py aircraft_app.apps.account.test
      
      - name: Run aircraft app unit tests
        run: |
          docker-compose exec -T web python manage.py aircraft_app.apps.aircraft.test
      
      - name: Run assembly app unit tests
        run: |
          docker-compose exec -T web python manage.py aircraft_app.apps.assembly.test
      - name: Run parts app unit tests
        run: |
          docker-compose exec -T web python manage.py aircraft_app.apps.parts.test

      - name: Run teams app unit tests
        run: |
          docker-compose exec -T web python manage.py aircraft_app.apps.teams.test
      
      - name: Tear down containers
        run: |
          docker-compose down